### PR TITLE
feat: Support Load

### PR DESCRIPTION
**Pull request by thiasB**
- according to [IPSO](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html) "load" Smart Object

- tested on hardware

### CODE REVIEW

**Comment by smlng** [comment]
thanks for contributing, may I ask:
- what is your use-case, as you said "tested on hardware": what load?
- and: do you know of any other CayenneLPP implementation that supports this type?

**Comment by smlng** [comment]
also there is weird merge-commit in this PR, can you please rebase on latest master to get rid of it and just have your single commit.

**Comment by thiasB** [comment]
- use case: for bee keepers, weight is one of the most relevant variables to monitor the colonies behavior in relation to weather conditions and food supply
- rebased to your lastest master

**Comment by smlng** [comment]
cool: bee keepers, didn't think about them and IoT together, but makes sense ... nice!

**Comment by thiasB** [comment]
Thanks. Much appreciated

**Pull request merged**
