### PR TITLE
Add unix time support

### PR DESCRIPTION
**Pull request by amotl**
This is a rebase of #42 on top of #50. Thanks @dolfandringa!

### CODE REVIEW

**Comment by smlng** [comment]
please rebase to latest master as #50 is merged now. 

Otherwise I'm a bit hesitant to merge this right away, bc it adds dependencies to datetime and tz not sure about support in micropython - though the status of micropython is a bit unclear to me, too

**Comment by amotl** [comment]
Dear Sebastian,

thanks for your comments. I've rebased this on top of current master and moved the `datetime` imports inline to at least improve things a bit regarding MicroPython compatibility.

Indeed, we are using the library on MicroPython through our [Terkin Datalogger](https://github.com/hiveeyes/terkin-datalogger) and would like it to stay compatible with MicroPython.

While I agree the support for the _Unix Time_ type probably still won't work on MicroPython yet, at least this is better than nothing for now.

With kind regards,
Andreas.

**Comment by amotl** [comment]
I will check whether the current implementation would work using the MicroPython `datetime` module.

```
Pycom MicroPython 1.20.2.rc6-0.10.2-vanilla-squirrel-nosmartconfig [v1.20.1.r2-122-gd82a6f43e-dirty] on 2020-03-06; FiPy with ESP32
Type "help()" for more information.
>>>
>>> from cayennelpp import LppFrame
>>> frame = LppFrame()
>>> frame.add_unix_time(0, 1590010843)

>>> print(frame)
LppFrame(data = [
  LppData(channel = 0, type = Unix Time, value = (1590010843,))
])

>>> frame.bytes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cayennelpp/lpp_frame.py", line 61, in bytes
  File "cayennelpp/lpp_data.py", line 61, in bytes
  File "cayennelpp/lpp_type.py", line 221, in lpp_unix_time_to_bytes
  File "datetime.py", line 1919, in <module>
  File "datetime.py", line 1836, in _create
AttributeError: type object 'tzinfo' has no attribute '__new__'
```

It does not work out of the box yet. Bummer!

**Comment by amotl** [comment]
> I will check whether the current implementation would work using the MicroPython datetime module.

I've investigated the matter within #53 and I am happy about the outcome. Through e1e4822, importing the module on MicroPython won't croak when the `datetime` module is not installed.

When the [`datetime.py`](https://github.com/daq-tools/pycopy-lib/blob/improve-datetime/datetime/datetime.py) is installed (with a fix provided through https://github.com/daq-tools/pycopy-lib/commit/5c8e8342 which has nothing to do with PyCayenneLPP), I've verified it to work flawlessly on Pycom MicroPython.

### Encode
```
Pycom MicroPython 1.20.2.rc6-0.10.2-vanilla-squirrel-nosmartconfig [v1.20.1.r2-122-gd82a6f43e-dirty] on 2020-03-06; FiPy with ESP32
Type "help()" for more information.
>>>
>>> from cayennelpp import LppFrame
>>> frame = LppFrame()
>>> frame.add_unix_time(0, 1590010843)
>>> frame.bytes()
bytearray(b'\x00\x85^\xc5\xa3\xdb')
```

### Decode
```
>>> print(LppFrame.from_bytes(b'\x00\x85^\xc5\xa3\xdb'))
LppFrame(data = [
  LppData(channel = 0, type = Unix Time, value = (datetime.datetime(2020, 5, 20, 21, 41, 20, tzinfo=datetime.timezone.utc),))
])
```

**Comment by smlng** [comment]
I thought about this and to me its best to omit `datetime` and `tz` and leave the conversion to the user, to keep functionality of this library simple. Also its confusing that when adding a timestamp one can use integer or datetime but the other way around will always return a `datetime` object.

Hence, I would basically use the same code as for the generic uint but with the correct type for unix timestamp and use integer as input and output. The user would then do something like 

```
from datetime import datetime
frame = LppFrame()
frame.add_unix_time(datetime.now().timestamp())

dt = datetime.fromtimestamp(frame.data[0].value)
```

**Comment by amotl** [comment]
Dear Sebastian,

> I thought about this and to me its best to omit datetime and tz and leave the conversion to the user, to keep functionality of this library simple.

I am fine with that. Will you add this snippet to the README somehow in order to guide users how to use it appropriately?

With kind regards,
Andreas.

**Pull request closed without merging**
